services:

  mongodb:
    image: aveliz0/menu-fusion-db:latest
    build:
      context: ./1-database
    container_name: menu_fusion_mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secret
      MONGO_INITDB_DATABASE: restaurante_fusion
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: always

  # ─── PENDIENTE: agregar servicio backend-api aqui ───
  # ─── PENDIENTE: agregar servicio frontend-ui aqui ────

volumes:
  mongo_data: