services:

  mongodb:
    image: aveliz0/menu-fusion-db:latest
    build:
      context: ./1-database
    container_name: menu_fusion_mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secret
      MONGO_INITDB_DATABASE: restaurante_fusion
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: always

  backend-api:
    image: llmiaull/api-menu-fusion:latest
    build:
      context: ./2-backend-api
    ports:
      - "8000:8000"
    environment:
      # Este es el "enlace" con los datos del servicio de arriba
      - MONGO_URL=mongodb://admin:secret@mongodb:27017/
    depends_on:
      # Esto asegura que arranque después de la BD
      - mongodb
  # ─── PENDIENTE: agregar servicio frontend-ui aqui ────

volumes:
  mongo_data:
